name: Yaml Lint
on: [push] 
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@ae1abb2821b567e96742aa776f7b62c9b6a26bc8
        with:
          file_or_dir: index.yaml
          config_data: "{extends: default, rules: {new-line-at-end-of-file: disable, document-start: disable, line-length: {max: 200}, trailing-spaces: disable}}"
