# Inspired by https://github.com/orgs/community/discussions/153608

name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 7 * * *'  # Daily at 07:00
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GIT_PUSH }}

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/original-repo-owner/original-repo.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Changes and Push
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
